### PR TITLE
fix: detection of maybeSingle

### LINKED ISSUE #361: Error logged when using `.maybeSingle()` returns no result
# Bug report

## Describe the bug

When selecting using `.maybeSingle()`, I'm getting an error logged to console if there's 0 rows returned. There's no error if I remove `.maybeSingle()`, and there's no error if a row is returned.

To be clear, the query still returns successfully.

image

The stack trace points to this line (probably badly source mapped):
https://github.com/supabase/postgrest-js/blob/84f151834a4e305508cd246cba9ea33e6affc0f2/src/PostgrestBuilder.ts#L102

## To Reproduce

```js
	const profileResult = await supabaseClient
		.from('profiles')
		.select()
		.eq('id', session.user.id)
		.maybeSingle()
```

## System information

- OS: macOS
- Browser: Brave
- Version of supabase-js: 2.0.4
- Version of Node.js: 16.15.0

### PR DESCRIPTION
**Pull request by steve-chavez**
Fixes #361.

On PostgREST 11.2.0, the format of the error got changed on PostgREST/postgrest#2876 to "The result contains 0 rows".

Change the detection to "0 rows". This should be backwards compatible.

### CODE REVIEW

File: src/PostgrestBuilder.ts [hunk 1]
```diff
@@ -149,7 +149,7 @@ export default abstract class PostgrestBuilder<Result>
           }
         }
 
-        if (error && this.isMaybeSingle && error?.details?.includes('Results contain 0 rows')) {
+        if (error && this.isMaybeSingle && error?.details?.includes('0 rows')) {
```
Comment (kamilogorek) [inline src/PostgrestBuilder.ts:152]: Is there a reason why we can't rely on error codes instead? Is this the fact that `ApiRequestErrorCode16` is an umbrella error for "incorrect number of rows", and not just 0?

Comment (soedirgo) [reply src/PostgrestBuilder.ts:152]: Yeah, we need to distinguish 0 rows from >1 rows

**Review by soedirgo — APPROVED** [review]

File: src/PostgrestBuilder.ts (hunk 1 above)
Comment (soedirgo) [reply src/PostgrestBuilder.ts:152]: Still not a fan of it though - ideally we can check this in a more robust manner
